package main

import "fmt"

type Skill struct {
	Name         string
	Abbreviation string
	Default      int
	Value        int
	Era          []Era
	Base         int
}

func (skill *Skill) String() string {
	return fmt.Sprintf("%s (%d)", skill.Abbreviation, skill.Value)
}

var Skills = map[string]Skill{
	"Accounting": {
		Name:         "Accounting",
		Abbreviation: "Accounting",
		Default:      5,
		Value:        5,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Anthropology": {
		Name:         "Accounting",
		Abbreviation: "Accounting",
		Default:      1,
		Value:        1,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Appraise": {
		Name:         "Appraise",
		Abbreviation: "Appraise",
		Default:      5,
		Value:        5,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Archaeology": {
		Name:         "Archaeology",
		Abbreviation: "Archaeology",
		Default:      1,
		Value:        1,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Art/Craft": {
		Name:         "Art/Craft",
		Abbreviation: "Art/Craft",
		Default:      5,
		Value:        5,
		Era:          []Era{Twenties, Modern},
		Base:         1,
	},
	"Charm": {
		Name:         "Charm",
		Abbreviation: "Charm",
		Default:      15,
		Value:        15,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Climb": {
		Name:         "Climb",
		Abbreviation: "Climb",
		Default:      20,
		Value:        20,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Computer Use": {
		Name:         "Computer Use",
		Abbreviation: "Computer Use",
		Default:      5,
		Value:        5,
		Era:          []Era{Modern},
	},
	"Credit Rating": {
		Name:         "Credit Rating",
		Abbreviation: "Credit Rating",
		Default:      0,
		Value:        0,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Cthulhu Mythos": {
		Name:         "Cthulhu Mythos",
		Abbreviation: "Cthulhu Mythos",
		Default:      0,
		Value:        0,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Disguise": {
		Name:         "Disguise",
		Abbreviation: "Disguise",
		Default:      5,
		Value:        5,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Drive Auto": {
		Name:         "Drive Auto",
		Abbreviation: "Drive Auto",
		Default:      20,
		Value:        20,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Electrical Repair": {
		Name:         "Electrical Repair",
		Abbreviation: "Elec. Repair",
		Default:      10,
		Value:        10,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Electronics": {
		Name:         "Electronics",
		Abbreviation: "Electronics",
		Default:      1,
		Value:        1,
		Era:          []Era{Modern},
	},
	"Fast Talk": {
		Name:         "Fast Talk",
		Abbreviation: "Fast Talk",
		Default:      5,
		Value:        5,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Fighting (Brawl)": {
		Name:         "Fighting (Brawl)",
		Abbreviation: "Fighting",
		Default:      25,
		Value:        25,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Fighting (Speciality)": {
		Name:         "Fighting (Speciality)",
		Abbreviation: "Fighting (Speciality)",
		Default:      25,
		Value:        25,
		Era:          []Era{Twenties, Modern},
		Base:         1,
	},
	"Firearms (Other)": {
		Name:         "Firearms (Other)",
		Abbreviation: "Firearms (Other)",
		Default:      1,
		Value:        1,
		Era:          []Era{Twenties, Modern},
		Base:         1,
	},
	"Firearms (Handgun)": {
		Name:         "Firearms (Handgun)",
		Abbreviation: "Handgun",
		Default:      20,
		Value:        20,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Firearms (Rifle/Shotgun)": {
		Name:         "Firearms (Rifle/Shotgun)",
		Abbreviation: "Rifle/Shotgun",
		Default:      25,
		Value:        25,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"First Aid": {
		Name:         "First Aid",
		Abbreviation: "First Aid",
		Default:      30,
		Value:        30,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"History": {
		Name:         "History",
		Abbreviation: "History",
		Default:      5,
		Value:        5,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Intimidate": {
		Name:         "Intimidate",
		Abbreviation: "Intimidate",
		Default:      15,
		Value:        15,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Jump": {
		Name:         "Jump",
		Abbreviation: "Jump",
		Default:      20,
		Value:        20,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Language(Other)": {
		Name:         "Language(Other)",
		Abbreviation: "Language(Other)",
		Default:      5,
		Value:        5,
		Era:          []Era{Twenties, Modern},
		Base:         1,
	},
	"Law": {
		Name:         "Law",
		Abbreviation: "Law",
		Default:      5,
		Value:        5,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Library Use": {
		Name:         "Library Use",
		Abbreviation: "Library Use",
		Default:      20,
		Value:        20,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Listen": {
		Name:         "Listen",
		Abbreviation: "Listen",
		Default:      20,
		Value:        20,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Locksmith": {
		Name:         "Locksmith",
		Abbreviation: "Locksmith",
		Default:      1,
		Value:        1,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Mech. Repair": {
		Name:         "Mechanical Repair",
		Abbreviation: "Mech. Repair",
		Default:      10,
		Value:        10,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Medicine": {
		Name:         "Medicine",
		Abbreviation: "Medicine",
		Default:      1,
		Value:        1,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Natural World": {
		Name:         "Natural World",
		Abbreviation: "Natural World",
		Default:      10,
		Value:        10,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Occult": {
		Name:         "Occult",
		Abbreviation: "Occult",
		Default:      5,
		Value:        5,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Persuade": {
		Name:         "Persuade",
		Abbreviation: "Persuade",
		Default:      10,
		Value:        10,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Pilot(Machine)": {
		Name:         "Pilot(Machine)",
		Abbreviation: "Pilot(Machine)",
		Default:      1,
		Value:        1,
		Era:          []Era{Twenties, Modern},
		Base:         1,
	},
	"Psychoanalysis": {
		Name:         "Psychoanalysis",
		Abbreviation: "Psychoanalysis",
		Default:      1,
		Value:        1,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Psychology": {
		Name:         "Psychology",
		Abbreviation: "Psychology",
		Default:      10,
		Value:        10,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Ride": {
		Name:         "Ride",
		Abbreviation: "Ride",
		Default:      5,
		Value:        5,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Science": {
		Name:         "Science(Base)",
		Abbreviation: "Science",
		Default:      1,
		Value:        1,
		Era:          []Era{Twenties, Modern},
		Base:         1,
	},
	"Sleight of Hand": {
		Name:         "Sleight of Hand",
		Abbreviation: "Sleight",
		Default:      10,
		Value:        10,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Spot Hidden": {
		Name:         "Spot Hidden",
		Abbreviation: "Spot Hidden",
		Default:      25,
		Value:        25,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Stealth": {
		Name:         "Stealth",
		Abbreviation: "Stealth",
		Default:      20,
		Value:        20,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Survival(Biome)": {
		Name:         "Survival(Biome)",
		Abbreviation: "Survival(Biome)",
		Default:      10,
		Value:        10,
		Era:          []Era{Twenties, Modern},
		Base:         1,
	},
	"Swim": {
		Name:         "Swim",
		Abbreviation: "Swim",
		Default:      20,
		Value:        20,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Throw": {
		Name:         "Throw",
		Abbreviation: "Throw",
		Default:      20,
		Value:        20,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Track": {
		Name:         "Track",
		Abbreviation: "Track",
		Default:      10,
		Value:        10,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
}
