// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Features() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section id=\"features\" class=\"py-5\"><div class=\"container\"><h2 class=\"text-center mb-5\">Why Choose CorbittFiles?</h2><div class=\"row g-4\"><div class=\"col-md-6 col-lg-3\"><div class=\"card feature-card shadow-sm p-4 text-center h-100\"><div class=\"icon-circle mx-auto mb-3\"><i class=\"bi bi-file-earmark-person fs-2\"></i></div><h5 class=\"fw-medium\">Tailored for Pulp Play</h5><p>Designed specifically for Call of Cthulhu v7 pulp investigators—fast, thematic, and immersive.</p></div></div><div class=\"col-md-6 col-lg-3\"><div class=\"card feature-card shadow-sm p-4 text-center h-100\"><div class=\"icon-circle mx-auto mb-3\"><i class=\"bi bi-shield-lock fs-2\"></i></div><h5 class=\"fw-medium\">Private & Secure</h5><p>No server storage—your characters live in browser cookies only, fully under your control.</p></div></div><div class=\"col-md-6 col-lg-3\"><div class=\"card feature-card shadow-sm p-4 text-center h-100\"><div class=\"icon-circle mx-auto mb-3\"><i class=\"bi bi-arrow-right-square fs-2\"></i></div><h5 class=\"fw-medium\">Seamless Export/Import</h5><p>Share or transfer investigators via unique codes—perfect for switching devices or playing with friends.</p></div></div><div class=\"col-md-6 col-lg-3\"><div class=\"card feature-card shadow-sm p-4 text-center h-100\"><div class=\"icon-circle mx-auto mb-3\"><i class=\"bi bi-piggy-bank fs-2\"></i></div><h5 class=\"fw-medium\">Zero Cost</h5><p>Completely free—no hidden fees or subscriptions, ever.</p></div></div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
