// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.865
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Footer() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<footer id=\"footer\" class=\"bg-dark text-white py-3\"><div class=\"container d-flex flex-column flex-md-row justify-content-between align-items-center\"><p class=\"mb-2 mb-md-0\">&copy; 2025 CorbittFiles. All rights reserved.</p><nav><a class=\"text-white me-3 footer-link\" data-bs-toggle=\"modal\" data-bs-target=\"#privacyModal\">Privacy Policy</a> <a class=\"text-white me-3 footer-link\" data-bs-toggle=\"modal\" data-bs-target=\"#termsModal\">Terms of Service</a> <a class=\"text-white footer-link\" data-bs-toggle=\"modal\" data-bs-target=\"#reportIssueModal\">Report Issue</a></nav></div></footer><!-- Floating Bug Report Button --><button class=\"bug-report-btn\" data-bs-toggle=\"modal\" data-bs-target=\"#reportIssueModal\" title=\"Report an Issue\"><i class=\"bi bi-bug-fill fs-4\"></i></button>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
