// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.865
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func StatusConditions() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"card shadow-sm mb-4\" style=\"border-radius: 1rem; border: none;\"><div class=\"card-header d-flex align-items-center p-3 card-header-custom\"><i class=\"bi bi-heart-pulse-fill me-2 card-header-icon\"></i><h4 class=\"section-title\">Status Conditions</h4></div><div class=\"card-body p-3\"><div class=\"d-flex flex-wrap gap-3\"><div class=\"form-check form-switch\"><input class=\"form-check-input editable\" type=\"checkbox\" role=\"switch\" id=\"temp-insanity\" style=\"cursor: pointer;\"> <label class=\"form-check-label\" for=\"temp-insanity\" style=\"cursor: pointer;\">Temporary Insanity</label></div><div class=\"form-check form-switch\"><input class=\"form-check-input editable\" type=\"checkbox\" role=\"switch\" id=\"indef-insanity\" style=\"cursor: pointer;\"> <label class=\"form-check-label\" for=\"indef-insanity\" style=\"cursor: pointer;\">Indefinite Insanity</label></div><div class=\"form-check form-switch\"><input class=\"form-check-input editable\" type=\"checkbox\" role=\"switch\" id=\"major-wound\" style=\"cursor: pointer;\"> <label class=\"form-check-label\" for=\"major-wound\" style=\"cursor: pointer;\">Major Wound</label></div><div class=\"form-check form-switch\"><input class=\"form-check-input editable\" type=\"checkbox\" role=\"switch\" id=\"unconscious\" style=\"cursor: pointer;\"> <label class=\"form-check-label\" for=\"unconscious\" style=\"cursor: pointer;\">Unconscious</label></div><div class=\"form-check form-switch\"><input class=\"form-check-input editable\" type=\"checkbox\" role=\"switch\" id=\"dying\" style=\"cursor: pointer;\"> <label class=\"form-check-label\" for=\"dying\" style=\"cursor: pointer;\">Dying</label></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
