package models

import (
	"fmt"
)

type Skill struct {
	Name         string `json:"Name"`
	FormName     string `json:"FormName"`
	Abbreviation string `json:"-"`
	Default      int    `json:"Default"`
	Value        int    `json:"Value"`
	Era          []Era  `json:"-"`
	Base         int    `json:"isBase"`
	Category     string `json:"Category"`
	NeedsFormDef int    `json:"needsFormDef"`
	IsSelected   bool   `json:"IsSelected"`
}

func (skill *Skill) String() string {
	return fmt.Sprintf("%s (%d)", skill.Abbreviation, skill.Value)
}

var Skills = map[string]Skill{
	"Accounting": {
		Name:         "Accounting",
		Abbreviation: "Accounting",
		FormName:     "Accounting",
		Default:      5,
		Value:        5,
		Era:          []Era{Twenties, Modern},
		Base:         0,
		IsSelected:   false,
	},
	"Anthropology": {
		Name:         "Anthropology",
		Abbreviation: "Anthropology",
		FormName:     "Anthropology",
		Default:      1,
		Value:        1,
		Era:          []Era{Twenties, Modern},
		Base:         0,
		IsSelected:   false,
	},
	"Appraise": {
		Name:         "Appraise",
		Abbreviation: "Appraise",
		FormName:     "Appraise",
		Default:      5,
		Value:        5,
		Era:          []Era{Twenties, Modern},
		Base:         0,
		IsSelected:   false,
	},
	"Archaeology": {
		Name:         "Archaeology",
		Abbreviation: "Archaeology",
		FormName:     "Archaeology",
		Default:      1,
		Value:        1,
		Era:          []Era{Twenties, Modern},
		Base:         0,
		IsSelected:   false,
	},
	"ArtCraft": {
		Name:         "ArtCraft",
		Abbreviation: "ArtCraft",
		FormName:     "ArtCraft1", // supports 1 more ArtCraft2
		Default:      5,
		Value:        5,
		Era:          []Era{Twenties, Modern},
		Base:         1,
		NeedsFormDef: 1,
		IsSelected:   false,
	},
	"Charm": {
		Name:         "Charm",
		Abbreviation: "Charm",
		FormName:     "Charm",
		Default:      15,
		Value:        15,
		Era:          []Era{Twenties, Modern},
		Base:         0,
		IsSelected:   false,
	},
	"Climb": {
		Name:         "Climb",
		Abbreviation: "Climb",
		FormName:     "Climb",
		Default:      20,
		Value:        20,
		Era:          []Era{Twenties, Modern},
		Base:         0,
		IsSelected:   false,
	},
	"Computer Use": {
		Name:         "Computer Use",
		Abbreviation: "Computer Use",
		FormName:     "Computer",
		Default:      5,
		Value:        5,
		Era:          []Era{Modern},
		Base:         0,
		IsSelected:   false,
	},
	"Credit Rating": {
		Name:         "Credit Rating",
		Abbreviation: "Credit Rating",
		FormName:     "Credit",
		Default:      0,
		Value:        0,
		Era:          []Era{Twenties, Modern},
		Base:         0,
		IsSelected:   false,
	},
	"Cthulhu Mythos": {
		Name:         "Cthulhu Mythos",
		Abbreviation: "Cthulhu Mythos",
		FormName:     "Cthulhu",
		Default:      0,
		Value:        0,
		Era:          []Era{Twenties, Modern},
		Base:         0,
		IsSelected:   false,
	},
	"Disguise": {
		Name:         "Disguise",
		Abbreviation: "Disguise",
		FormName:     "Disguise",
		Default:      5,
		Value:        5,
		Era:          []Era{Twenties, Modern},
		Base:         0,
		IsSelected:   false,
	},
	"Drive Auto": {
		Name:         "Drive Auto",
		Abbreviation: "Drive Auto",
		FormName:     "Drive",
		Default:      20,
		Value:        20,
		Era:          []Era{Twenties, Modern},
		Base:         0,
		IsSelected:   false,
	},
	"Electrical Repair": {
		Name:         "Electrical Repair",
		Abbreviation: "Elec. Repair",
		FormName:     "ElecRepair",
		Default:      10,
		Value:        10,
		Era:          []Era{Twenties, Modern},
		Base:         0,
		IsSelected:   false,
	},
	"Electronics": {
		Name:         "Electronics",
		Abbreviation: "Electronics",
		FormName:     "Electronic",
		Default:      1,
		Value:        1,
		Era:          []Era{Modern},
		Base:         0,
		IsSelected:   false,
	},
	"Fast Talk": {
		Name:         "Fast Talk",
		Abbreviation: "Fast Talk",
		FormName:     "FastTalk ",
		Default:      5,
		Value:        5,
		Era:          []Era{Twenties, Modern},
		Base:         0,
		IsSelected:   false,
	},
	"Fighting(Brawl)": {
		Name:         "Fighting(Brawl)",
		Abbreviation: "Fighting",
		FormName:     "Fighting",
		Default:      25,
		Value:        25,
		Era:          []Era{Twenties, Modern},
		Base:         0,
		Category:     "Fighting",
		IsSelected:   false,
	},
	"Fighting": {
		Name:         "Fighting",
		Abbreviation: "Fighting",
		FormName:     "Fighting1",
		Default:      1,
		Value:        1,
		Era:          []Era{Twenties, Modern},
		Base:         1,
		NeedsFormDef: 1,
		IsSelected:   false,
	},
	"Firearms": {
		Name:         "Firearms",
		Abbreviation: "Firearms",
		FormName:     "Firearms",
		Default:      1,
		Value:        1,
		Era:          []Era{Twenties, Modern},
		Base:         1,
		NeedsFormDef: 1,
		IsSelected:   false,
	},
	"Firearms(Handgun)": {
		Name:         "Firearms(Handgun)",
		Abbreviation: "Handgun",
		FormName:     "FirearmsHandguns",
		Default:      20,
		Value:        20,
		Era:          []Era{Twenties, Modern},
		Base:         0,
		Category:     "Firearms",
		IsSelected:   false,
	},
	"Firearms(Rifle/Shotgun)": {
		Name:         "Firearms(Rifle/Shotgun)",
		Abbreviation: "Rifle/Shotgun",
		FormName:     "FirearmsRifles",
		Default:      25,
		Value:        25,
		Era:          []Era{Twenties, Modern},
		Base:         0,
		Category:     "Firearms",
		IsSelected:   false,
	},
	"First Aid": {
		Name:         "First Aid",
		Abbreviation: "First Aid",
		FormName:     "FirstAid",
		Default:      30,
		Value:        30,
		Era:          []Era{Twenties, Modern},
		Base:         0,
		IsSelected:   false,
	},
	"History": {
		Name:         "History",
		Abbreviation: "History",
		FormName:     "History",
		Default:      5,
		Value:        5,
		Era:          []Era{Twenties, Modern},
		Base:         0,
		IsSelected:   false,
	},
	"Intimidate": {
		Name:         "Intimidate",
		Abbreviation: "Intimidate",
		FormName:     "Intimidate",
		Default:      15,
		Value:        15,
		Era:          []Era{Twenties, Modern},
		Base:         0,
		IsSelected:   false,
	},
	"Jump": {
		Name:         "Jump",
		Abbreviation: "Jump",
		FormName:     "Jump",
		Default:      20,
		Value:        20,
		Era:          []Era{Twenties, Modern},
		Base:         0,
		IsSelected:   false,
	},
	"Language": {
		Name:         "Language",
		Abbreviation: "Language",
		FormName:     "OtherLanguage", // holds up to 3
		Default:      5,
		Value:        5,
		Era:          []Era{Twenties, Modern},
		Base:         1,
		NeedsFormDef: 1,
		IsSelected:   false,
	},
	"Law": {
		Name:         "Law",
		Abbreviation: "Law",
		FormName:     "Law",
		Default:      5,
		Value:        5,
		Era:          []Era{Twenties, Modern},
		Base:         0,
		IsSelected:   false,
	},
	"Library Use": {
		Name:         "Library Use",
		Abbreviation: "Library Use",
		FormName:     "Library",
		Default:      20,
		Value:        20,
		Era:          []Era{Twenties, Modern},
		Base:         0,
		IsSelected:   false,
	},
	"Listen": {
		Name:         "Listen",
		Abbreviation: "Listen",
		FormName:     "Listen",
		Default:      20,
		Value:        20,
		Era:          []Era{Twenties, Modern},
		Base:         0,
		IsSelected:   false,
	},
	"Locksmith": {
		Name:         "Locksmith",
		Abbreviation: "Locksmith",
		FormName:     "Locksmith",
		Default:      1,
		Value:        1,
		Era:          []Era{Twenties, Modern},
		Base:         0,
		IsSelected:   false,
	},
	"Mechanical Repair": {
		Name:         "Mechanical Repair",
		Abbreviation: "Mech. Repair",
		FormName:     "MechRepair",
		Default:      10,
		Value:        10,
		Era:          []Era{Twenties, Modern},
		Base:         0,
		IsSelected:   false,
	},
	"Medicine": {
		Name:         "Medicine",
		Abbreviation: "Medicine",
		FormName:     "Medicine",
		Default:      1,
		Value:        1,
		Era:          []Era{Twenties, Modern},
		Base:         0,
		IsSelected:   false,
	},
	"Natural World": {
		Name:         "Natural World",
		Abbreviation: "Natural World",
		FormName:     "NaturalWorld",
		Default:      10,
		Value:        10,
		Era:          []Era{Twenties, Modern},
		Base:         0,
		IsSelected:   false,
	},
	"Occult": {
		Name:         "Occult",
		Abbreviation: "Occult",
		FormName:     "Occult",
		Default:      5,
		Value:        5,
		Era:          []Era{Twenties, Modern},
		Base:         0,
		IsSelected:   false,
	},
	"Persuade": {
		Name:         "Persuade",
		Abbreviation: "Persuade",
		FormName:     "Persuade",
		Default:      10,
		Value:        10,
		Era:          []Era{Twenties, Modern},
		Base:         0,
		IsSelected:   false,
	},
	"Pilot": {
		Name:         "Pilot",
		Abbreviation: "Pilot",
		FormName:     "Pilot",
		Default:      1,
		Value:        1,
		Era:          []Era{Twenties, Modern},
		Base:         1,
		NeedsFormDef: 1,
		IsSelected:   false,
	},
	"Psychoanalysis": {
		Name:         "Psychoanalysis",
		Abbreviation: "Psychoanalysis",
		FormName:     "Psychoanalysis",
		Default:      1,
		Value:        1,
		Era:          []Era{Twenties, Modern},
		Base:         0,
		IsSelected:   false,
	},
	"Psychology": {
		Name:         "Psychology",
		Abbreviation: "Psychology",
		FormName:     "Psyschology", // Note: Original key has a typo
		Default:      10,
		Value:        10,
		Era:          []Era{Twenties, Modern},
		Base:         0,
		IsSelected:   false,
	},
	"Ride": {
		Name:         "Ride",
		Abbreviation: "Ride",
		FormName:     "Ride",
		Default:      5,
		Value:        5,
		Era:          []Era{Twenties, Modern},
		Base:         0,
		IsSelected:   false,
	},
	"Science": {
		Name:         "Science",
		Abbreviation: "Science",
		FormName:     "Science1",
		Default:      1,
		Value:        1,
		Era:          []Era{Twenties, Modern},
		Base:         1,
		NeedsFormDef: 1, // Can hold up to 3  Science, Science1, ...2, IsSelected: false,
	},
	"Sleight of Hand": {
		Name:         "Sleight of Hand",
		Abbreviation: "Sleight",
		FormName:     "Sleight",
		Default:      10,
		Value:        10,
		Era:          []Era{Twenties, Modern},
		Base:         0,
		IsSelected:   false,
	},
	"Spot Hidden": {
		Name:         "Spot Hidden",
		Abbreviation: "Spot Hidden",
		FormName:     "SpotHidden",
		Default:      25,
		Value:        25,
		Era:          []Era{Twenties, Modern},
		Base:         0,
		IsSelected:   false,
	},
	"Stealth": {
		Name:         "Stealth",
		Abbreviation: "Stealth",
		FormName:     "Stealth",
		Default:      20,
		Value:        20,
		Era:          []Era{Twenties, Modern},
		Base:         0,
		IsSelected:   false,
	},
	"Survival": {
		Name:         "Survival",
		Abbreviation: "Survival",
		FormName:     "Survival",
		Default:      10,
		Value:        10,
		Era:          []Era{Twenties, Modern},
		Base:         1,
		NeedsFormDef: 1,
		IsSelected:   false,
	},
	"Swim": {
		Name:         "Swim",
		Abbreviation: "Swim",
		FormName:     "Swim",
		Default:      20,
		Value:        20,
		Era:          []Era{Twenties, Modern},
		Base:         0,
		IsSelected:   false,
	},
	"Throw": {
		Name:         "Throw",
		Abbreviation: "Throw",
		FormName:     "Throw",
		Default:      20,
		Value:        20,
		Era:          []Era{Twenties, Modern},
		Base:         0,
		IsSelected:   false,
	},
	"Track": {
		Name:         "Track",
		Abbreviation: "Track",
		FormName:     "Track",
		Default:      10,
		Value:        10,
		Era:          []Era{Twenties, Modern},
		Base:         0,
		IsSelected:   false,
	},
	"Navigate": {
		Name:         "Navigate",
		Abbreviation: "Navigate",
		FormName:     "Navigate",
		Default:      10,
		Value:        10,
		Era:          []Era{Twenties, Modern},
		Base:         0,
		IsSelected:   false,
	},
}
