package models

import (
	"fmt"
)

type Skill struct {
	Name         string `json:"-"`
	Abbreviation string `json:"-"`
	Default      int    `json:"-"`
	Value        int    `json:"value"`
	Era          []Era  `json:"-"`
	Base         int    `json:"isBase"`
}

func (skill *Skill) String() string {
	return fmt.Sprintf("%s (%d)", skill.Abbreviation, skill.Value)
}

// the weird skill key names are so they match the pdf form fields.
var Skills = map[string]Skill{
	"Accounting": {
		Name:         "Accounting",
		Abbreviation: "Accounting",
		Default:      5,
		Value:        5,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Anthropology": {
		Name:         "Accounting",
		Abbreviation: "Accounting",
		Default:      1,
		Value:        1,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Appraise": {
		Name:         "Appraise",
		Abbreviation: "Appraise",
		Default:      5,
		Value:        5,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Archaeology": {
		Name:         "Archaeology",
		Abbreviation: "Archaeology",
		Default:      1,
		Value:        1,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"ArtCraft1": {
		Name:         "ArtCraft",
		Abbreviation: "ArtCraft",
		Default:      5,
		Value:        5,
		Era:          []Era{Twenties, Modern},
		Base:         1,
	},
	"Charm": {
		Name:         "Charm",
		Abbreviation: "Charm",
		Default:      15,
		Value:        15,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Climb": {
		Name:         "Climb",
		Abbreviation: "Climb",
		Default:      20,
		Value:        20,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Computer": {
		Name:         "Computer Use",
		Abbreviation: "Computer Use",
		Default:      5,
		Value:        5,
		Era:          []Era{Modern},
	},
	"Credit": {
		Name:         "Credit Rating",
		Abbreviation: "Credit Rating",
		Default:      0,
		Value:        0,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Cthulhu": {
		Name:         "Cthulhu Mythos",
		Abbreviation: "Cthulhu Mythos",
		Default:      0,
		Value:        0,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Disguise": {
		Name:         "Disguise",
		Abbreviation: "Disguise",
		Default:      5,
		Value:        5,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Drive": {
		Name:         "Drive Auto",
		Abbreviation: "Drive Auto",
		Default:      20,
		Value:        20,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"ElecRepair": {
		Name:         "Electrical Repair",
		Abbreviation: "Elec. Repair",
		Default:      10,
		Value:        10,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Electronic": {
		Name:         "Electronics",
		Abbreviation: "Electronics",
		Default:      1,
		Value:        1,
		Era:          []Era{Modern},
	},
	"FastTalk": {
		Name:         "Fast Talk",
		Abbreviation: "Fast Talk",
		Default:      5,
		Value:        5,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Fighting": {
		Name:         "Fighting (Brawl)",
		Abbreviation: "Fighting",
		Default:      25,
		Value:        25,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Fighting (Speciality)": {
		Name:         "Fighting (Speciality)",
		Abbreviation: "Fighting (Speciality)",
		Default:      25,
		Value:        25,
		Era:          []Era{Twenties, Modern},
		Base:         1,
	},
	"Firearms (Other)": {
		Name:         "Firearms (Other)",
		Abbreviation: "Firearms (Other)",
		Default:      1,
		Value:        1,
		Era:          []Era{Twenties, Modern},
		Base:         1,
	},
	"FirearmsHandguns": {
		Name:         "Firearms (Handgun)",
		Abbreviation: "Handgun",
		Default:      20,
		Value:        20,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"FirearmsRifles": {
		Name:         "Firearms (Rifle/Shotgun)",
		Abbreviation: "Rifle/Shotgun",
		Default:      25,
		Value:        25,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"FirstAid": {
		Name:         "First Aid",
		Abbreviation: "First Aid",
		Default:      30,
		Value:        30,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"History": {
		Name:         "History",
		Abbreviation: "History",
		Default:      5,
		Value:        5,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Intimidate": {
		Name:         "Intimidate",
		Abbreviation: "Intimidate",
		Default:      15,
		Value:        15,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Jump": {
		Name:         "Jump",
		Abbreviation: "Jump",
		Default:      20,
		Value:        20,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Language(Other)": {
		Name:         "Language(Other)",
		Abbreviation: "Language(Other)",
		Default:      5,
		Value:        5,
		Era:          []Era{Twenties, Modern},
		Base:         1,
	},
	"Law": {
		Name:         "Law",
		Abbreviation: "Law",
		Default:      5,
		Value:        5,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Library": {
		Name:         "Library Use",
		Abbreviation: "Library Use",
		Default:      20,
		Value:        20,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Listen": {
		Name:         "Listen",
		Abbreviation: "Listen",
		Default:      20,
		Value:        20,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Locksmith": {
		Name:         "Locksmith",
		Abbreviation: "Locksmith",
		Default:      1,
		Value:        1,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"MechRepair": {
		Name:         "Mechanical Repair",
		Abbreviation: "Mech. Repair",
		Default:      10,
		Value:        10,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Medicine": {
		Name:         "Medicine",
		Abbreviation: "Medicine",
		Default:      1,
		Value:        1,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"NaturalWorld": {
		Name:         "Natural World",
		Abbreviation: "Natural World",
		Default:      10,
		Value:        10,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Occult": {
		Name:         "Occult",
		Abbreviation: "Occult",
		Default:      5,
		Value:        5,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Persuade": {
		Name:         "Persuade",
		Abbreviation: "Persuade",
		Default:      10,
		Value:        10,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Pilot": {
		Name:         "Pilot(Machine)",
		Abbreviation: "Pilot(Machine)",
		Default:      1,
		Value:        1,
		Era:          []Era{Twenties, Modern},
		Base:         1,
	},
	"Psychoanalysis": {
		Name:         "Psychoanalysis",
		Abbreviation: "Psychoanalysis",
		Default:      1,
		Value:        1,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Psyschology": {
		Name:         "Psychology",
		Abbreviation: "Psychology",
		Default:      10,
		Value:        10,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Ride": {
		Name:         "Ride",
		Abbreviation: "Ride",
		Default:      5,
		Value:        5,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Science": {
		Name:         "Science(Base)",
		Abbreviation: "Science",
		Default:      1,
		Value:        1,
		Era:          []Era{Twenties, Modern},
		Base:         1,
	},
	"Sleight": {
		Name:         "Sleight of Hand",
		Abbreviation: "Sleight",
		Default:      10,
		Value:        10,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"SpotHidden": {
		Name:         "Spot Hidden",
		Abbreviation: "Spot Hidden",
		Default:      25,
		Value:        25,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Stealth": {
		Name:         "Stealth",
		Abbreviation: "Stealth",
		Default:      20,
		Value:        20,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Survival": {
		Name:         "Survival(Biome)",
		Abbreviation: "Survival(Biome)",
		Default:      10,
		Value:        10,
		Era:          []Era{Twenties, Modern},
		Base:         1,
	},
	"Swim": {
		Name:         "Swim",
		Abbreviation: "Swim",
		Default:      20,
		Value:        20,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Throw": {
		Name:         "Throw",
		Abbreviation: "Throw",
		Default:      20,
		Value:        20,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Track": {
		Name:         "Track",
		Abbreviation: "Track",
		Default:      10,
		Value:        10,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
	"Navigate": {
		Name:         "Navigate",
		Abbreviation: "Navigate",
		Default:      10,
		Value:        10,
		Era:          []Era{Twenties, Modern},
		Base:         0,
	},
}

var SkillsToFormName = map[string]string{
	"Accounting":               "Accounting",
	"Appraise":                 "Appraise",
	"Archaeology":              "Archaeology",
	"ArtCraft":                 "ArtCraft1",
	"Charm":                    "Charm",
	"Climb":                    "Climb",
	"Computer Use":             "Computer",
	"Credit Rating":            "Credit",
	"Cthulhu Mythos":           "Cthulhu",
	"Disguise":                 "Disguise",
	"Drive Auto":               "Drive",
	"Electrical Repair":        "ElecRepair",
	"Electronics":              "Electronic",
	"Fast Talk":                "FastTalk",
	"Fighting (Brawl)":         "Fighting",
	"Fighting (Speciality)":    "Fighting (Speciality)",
	"Firearms (Other)":         "Firearms (Other)",
	"Firearms (Handgun)":       "FirearmsHandguns",
	"Firearms (Rifle/Shotgun)": "FirearmsRifles",
	"First Aid":                "FirstAid",
	"History":                  "History",
	"Intimidate":               "Intimidate",
	"Jump":                     "Jump",
	"Language(Other)":          "Language(Other)",
	"Law":                      "Law",
	"Library Use":              "Library",
	"Listen":                   "Listen",
	"Locksmith":                "Locksmith",
	"Mechanical Repair":        "MechRepair",
	"Medicine":                 "Medicine",
	"Natural World":            "NaturalWorld",
	"Occult":                   "Occult",
	"Persuade":                 "Persuade",
	"Pilot(Machine)":           "Pilot",
	"Psychoanalysis":           "Psychoanalysis",
	"Psychology":               "Psyschology",
	"Ride":                     "Ride",
	"Science(Base)":            "Science",
	"Sleight of Hand":          "Sleight",
	"Spot Hidden":              "SpotHidden",
	"Stealth":                  "Stealth",
	"Survival(Biome)":          "Survival",
	"Swim":                     "Swim",
	"Throw":                    "Throw",
	"Track":                    "Track",
	"Navigate":                 "Navigate",
}
